apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:PsvYeZCZn5Q52ocb,iv:mkd4LJ0tme/uKk73izU4TthkdtDdO7E53GHnmLRwnrc=,tag:7yOJQPzGI6Jn7XiFJ0I97g==,type:str]
sops:
  age:
    - recipient: age17kvqxk5lcd8z64k43d4cgu36av7k7n3wl4377pr0jxtzp2g2c44sd3e2kx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VGczZnJ2b1lOR1MxZmtS
        bHRwLzhYUC81YnVNYkdCZGM3aHZCTm5VcEIwCldFVHg4Y2VCUHhXbUY1b3c2V2Ir
        Nk5ZbFkrTHkrTlJtN0NTSU1GNkJjYWMKLS0tIENYTCtsdS9kTW1SSE5JWWEvQS9a
        eis4aklDOW5EeXc0WjJxZ1N1aDR1VG8KWMaHU6qTb1jTMX5RGYwvmPYKeOLmrECd
        zEBp8/Bfr4a/HGjuC89L9zSp4v1XCMEx5Kpvvm/FHAXDvmTyAIFdJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T01:51:50Z"
  mac: ENC[AES256_GCM,data:1FcrqjbZeV0rsrmhZRr5/UycGnTvLTCDsl0V9AYnYhB48t1PIfU+LY0r6PN6BGAp9qxcT/MHCGs6M+K8YpzWTmsrFqKBqGZIQGhXepdDzOb0eJ3QreR/12NJ3DmAviGdVDUYQ38vmJzZdHWN4ijn8B2jCWfC5VsOwWOftuIlqLo=,iv:KR1TseSgxgsp2tSz9kxahy4SzPV9WePBqz1rC4zreao=,tag:uHvqg/qrlNDp2f5zn2EP1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
