apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:OFDjtOU+6c06gsAyYON/sq2hUPDR0noTrG8RVGEzGr8ANjM7wAPUJ4SWIi3y2G84+WX5O/9V/noovp+ySP3Os2DlLP+DpwUrqPung0RERF5QUTaZx5wGW2OvCSVl6RFs6sVvQRzMspCF3vRu+2rMBuROU22fLTEyGjA6xl3/0tY/ZIDxQrmxvterFb/GplfSUkfnIxNik5fbbh9gFrpx96pvr9Oq0j60aykQyKBX1ykJpbu/,iv:XpaXedMw4tQv8Skoopae4dA1OG8g3MWc/n/x2dRU4G8=,tag:+QfWRpXuLgGicN5dhtTOEA==,type:str]
sops:
  age:
    - recipient: age17kvqxk5lcd8z64k43d4cgu36av7k7n3wl4377pr0jxtzp2g2c44sd3e2kx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEa2F0R1VjNi9yVE44RHdk
        aVZjaWhxank1V1hvMCtKeXYyZGh3R29ZNFhBCnFWTkdOb0M4TSt5R3ZVaUhDOWdo
        aEZnQW9sV0MybVV6Rkt0QlpmZUtWSUUKLS0tIFIydkpkU3QwcE5JR0pqcWhqblk4
        aSt5WkI3N1haV3dNMnhmV1lGLzIrTTgKPpeGKH+cOWq+lCoyhT8DTYBaPUVgg556
        7fTaTHLKjKUYUfPmyruSo9s4VA5w1TWopJ+xZpLXjwCqDmKjxXzBUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T01:51:50Z"
  mac: ENC[AES256_GCM,data:A78Z1oCbLHqLGfsYBbvI6fMJXWD2AHTRaa4HUnCFzFgiPMFXaL7lflCCcaucST/9D5k9DUUrHov21WvqyIrBc/jbA+BOc7tYvs7BNiRWJP27MkIZoGfaaoiR3jjcmuy7tJAPmReLMQN5FeoqFnFUVzxYmcxbgnUz+Knq+XMAAIA=,iv:Btie2Farm4ucfYA/3ljdDv5pyygNJLvX9fJMNhpqY38=,tag:jfKC8KaZf5PIiRoPY7MbiQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
